/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 neuron.gltf --transform 
Files: neuron.gltf [3.27MB] > neuron-transformed.glb [10.5MB] (-221%)
Author: mmarynguyen (https://sketchfab.com/mmarynguyen)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/neuron-03a5173f3d2e46958b6f8be81b1c88be
Title: Neuron
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/neuron-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.lysosome_lysosome3_0.geometry}
        material={materials.PaletteMaterial001}
        scale={0.4}
      />
      <mesh
        geometry={nodes.neuron_Neuron_0.geometry}
        material={materials.PaletteMaterial002}
        scale={0.4}
      />
      <mesh
        geometry={nodes.pasted__pSphere1_aiStandardSurface2_0.geometry}
        material={materials.PaletteMaterial003}
        scale={0.4}
      />
      <mesh
        geometry={nodes.Nucleus1_Nucleus_0.geometry}
        material={materials.PaletteMaterial004}
        scale={0.4}
      />
      <mesh
        geometry={nodes.Nucleolus_nucleolus_0.geometry}
        material={materials.PaletteMaterial005}
        scale={0.4}
      />
      <mesh
        geometry={nodes.pasted__pTorus1_mito_0.geometry}
        material={materials.PaletteMaterial006}
        scale={0.4}
      />
    </group>
  );
}

useGLTF.preload("/neuron-transformed.glb");
